export const EventItems = [
    {
        title: 'event nafme',
        url: 'https://github.com/Mhc-ksa/ksa-react-website',
        thumbnail: 'https://imageio.forbes.com/specials-images/imageserve/60269ef7ada7085ce688069b/Cyber-Security-and-Digital-Data-Protection-Concept/960x0.jpg?fit=bounds&format=jpg&width=960',
        location: 'kendade 305',
        date: new Date(2023,0,6,17),
        startTime: 3,
        duration: 1,
    },
    {
        title: 'event name',
        url: 'https://github.com/Mhc-ksa/ksa-react-website',
        thumbnail: 'https://www.dhs.gov/sites/default/files/images/st/Our-Work/20_0112_st_cybersecurity1.jpg',
        location: 'kendade 305',
        date: new Date(2023,0,6,17),
        startTime: 3,
        duration: 1,
    },
    {
        title: 'event name',
        url: 'https://github.com/Mhc-ksa/ksa-react-website',
        thumbnail: 'https://www.dhs.gov/sites/default/files/images/st/Our-Work/20_0112_st_cybersecurity1.jpg',
        location: 'kendade 305',
        date: new Date(2022,10,6,17),
        startTime: 3,
        duration: 1,
    },
    {
        title: 'event name',
        url: 'https://github.com/Mhc-ksa/ksa-react-website',
        thumbnail: 'https://www.dhs.gov/sites/default/files/images/st/Our-Work/20_0112_st_cybersecurity1.jpg',
        location: 'kendade 305',
        date: new Date(2022,0,6,17),
        startTime: 3,
        duration: 1,
    },
    {
        title: 'event name',
        url: 'https://github.com/Mhc-ksa/ksa-react-website',
        thumbnail: 'https://www.dhs.gov/sites/default/files/images/st/Our-Work/20_0112_st_cybersecurity1.jpg',
        location: 'kendade 305',
        date: new Date(2021,10,6,17),
        startTime: 3,
        duration: 1,
    },
    {
        title: 'event name',
        url: 'https://github.com/Mhc-ksa/ksa-react-website',
        thumbnail: 'https://www.dhs.gov/sites/default/files/images/st/Our-Work/20_0112_st_cybersecurity1.jpg',
        location: 'kendade 305',
        date: new Date(2021,0,6,17),
        startTime: 3,
        duration: 1,
    },
]
